pipeline {
    agent {
        label 'master'
    }
    
    stages {
        stage('Run Python Script') {
            steps {
                echo "Running add2vals.py with arguments 5 and 5..."
                // Run the add2vals.py script with arguments 5 and 5
                sh '''
                python3 sources/add2vals.py 5 5
                '''
                // Stash the results if needed for later use
                stash(name: 'compiled-results', includes: 'sources/*.py*')
            }
        }
    }
    
    post {
        always {
            // Unstash the results if needed in later stages
            unstash 'compiled-results'
            echo "Stashed Python scripts and bytecode."
        }
    }
}
