pipeline {
    agent {
        label 'master'
    }
    stages {
        stage('Run Python Scripts') {
            steps {
                echo "Running Python scripts..."
                // Run the Python scripts and echo the output
                sh '''
                for script in sources/*.py; do
                    echo "Running $script..."
                    python3 $script
                done
                '''
                // Stash the results for later use
                stash(name: 'compiled-results', includes: 'sources/*.py*')
            }
        }
        
    }
    
}
